#!/usr/bin/env python3
"""Summarise one or more `run_context_ablation.py` output bundles as Markdown.

Each `outputs/<name>/ablation_summary.json` records the three-condition
ablation (`off` / `title_abstract` / `retrieved_chunks`) for one
(clip, artifact, min_source_mass) triple. This script turns a pile of
those JSONs into a single Markdown table — useful for the paper writeup
and for diffing sweeps without reloading models.

No GPU, no model load. Deterministic.

Usage:
    python compare_context_ablations.py outputs/context_ablation_ccp75 \
        outputs/context_ablation_ccp75_guard03 \
        outputs/context_ablation_oiqewd90 \
        outputs/context_ablation_oiqewd90_guard03 \
        --out outputs/context_ablation_comparison.md
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


def load_summary(path: Path) -> dict[str, Any]:
    if path.is_dir():
        path = path / "ablation_summary.json"
    return json.loads(path.read_text(encoding="utf-8"))


def format_run_label(summary: dict[str, Any], fallback: str) -> str:
    wav_stem = Path(str(summary.get("wav", ""))).stem or "?"
    mass = summary.get("translation_alignatt_min_source_mass")
    mass_s = "off" if mass in (None, 0.0) else f"{mass:g}"
    top_k = summary.get("paper_context_top_k", "?")
    max_chars = summary.get("paper_context_max_chars", "?")
    return (
        f"{fallback}\n\n"
        f"- clip: `{wav_stem}`\n"
        f"- artifact: `{Path(str(summary.get('paper_context_path',''))).name}`\n"
        f"- source/target: `{summary.get('source_language_code','?')}→{summary.get('target_language_code','?')}`\n"
        f"- chunk_ms: `{summary.get('chunk_ms','?')}`\n"
        f"- top_k: `{top_k}`, max_chars: `{max_chars}`\n"
        f"- provenance guard (min_source_mass): **{mass_s}**\n"
        f"- model_load_ms: `{summary.get('model_load_ms','?')}`"
    )


def format_condition_row(condition: dict[str, Any]) -> str:
    def fmt_float(x: Any, ndigits: int = 3) -> str:
        if x is None:
            return "—"
        try:
            return f"{float(x):.{ndigits}f}"
        except (TypeError, ValueError):
            return str(x)

    return (
        f"| `{condition['mode']}` "
        f"| {fmt_float(condition.get('rtf'))} "
        f"| {fmt_float(condition.get('wallclock_s'), 1)} "
        f"| {condition.get('num_updates','?')} "
        f"| {fmt_float(condition.get('first_emit_audio_s'), 2)} "
        f"| {fmt_float(condition.get('mean_word_delay_ms'), 1)} "
        "|"
    )


def render_run_markdown(summary: dict[str, Any], fallback_label: str) -> str:
    header = (
        "| mode | RTF | wallclock_s | updates | first_emit_audio_s | mean_word_delay_ms |\n"
        "|---|---|---|---|---|---|\n"
    )
    rows = "\n".join(format_condition_row(c) for c in summary.get("conditions", []))
    label = format_run_label(summary, fallback_label)
    translations = "\n".join(
        f"- **`{c['mode']}`**: {c.get('final_translation','').strip()}"
        for c in summary.get("conditions", [])
    )
    return (
        f"## {label}\n\n"
        f"{header}{rows}\n\n"
        f"### Final translations\n\n{translations}\n"
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "runs",
        nargs="+",
        help="Paths to `ablation_summary.json` files or parent directories.",
    )
    parser.add_argument(
        "--out",
        default=None,
        help="Write the Markdown report to this path (else stdout).",
    )
    args = parser.parse_args()

    sections: list[str] = [
        "# Context-ablation comparison\n\n"
        "Generated by `compare_context_ablations.py` from "
        "`ablation_summary.json` bundles.\n"
    ]
    for run in args.runs:
        summary = load_summary(Path(run))
        sections.append(render_run_markdown(summary, fallback_label=Path(run).name))

    report = "\n".join(sections).rstrip() + "\n"
    if args.out:
        out_path = Path(args.out)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(report, encoding="utf-8")
        print(f"Wrote {out_path}")
    else:
        print(report)


if __name__ == "__main__":
    main()
